### ISSUE TITLE
新版本可能导致的解题答案抄袭问题。

### ISSUE THREAD

**Issue by B1ue1nWh1te** [chainflag/eth-challenge-base#22]
注意到在近期更新中将 eth_getBlockByHash 、 eth_getBlockByNumber 等与区块查询相关的 RPC API 默认设置为开放状态，我明白这是为了让 Remix 、 Metamask 等工具也能在题目环境链中正常运行，但这同时也意味着存在通过扫描所有区块交易并复刻抄袭其他选手解题答案的可能。
即假设某题目已经有解，那么只需通过 eth_getBlockByNumber 向前扫描每个区块以获取每个区块中包含的交易哈希，并根据这些交易哈希逐个通过 eth_getTransactionByHash 获取交易收据详情，是存在答案抄袭的可能性的（尽管这或许非常耗时）。
我并没有非常好的解决办法，因为我也认为需要让题目环境尽可能兼容所有的工具，希望团队能有更好的解决方案、或是显著提示有高度保密需求的开发者应该如何配置。

**Comment by B1ue1nWh1te** [comment]
刚刚又去看了一遍，发现团队已经将 transaction 置空了，那么目前看来应该是没问题的。

**Comment by iczc** [comment]
> 刚刚又去看了一遍，发现团队已经将 transaction 置空了，那么目前看来应该是没问题的。

最近我将 proxy 的实现从完全禁用 `eth_getBlockByHash` 和 `eth_getBlockByNumber` RPC 方法修改为清理掉它们 response 中的 transactions 字段，这可以解决之前 remix 等工具无法正常使用题目测试链的问题。
我将会在之后将新的防抄袭实现原理更新到readme的介绍中，以免造成误解。
